spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.16.50.245:3306/nnd
    url: jdbc:mysql://172.16.20.245:3306/testspring
    username: root
    password: mysql@duanrong
#    password: ENC(eWMw29sBhhtYAOkOX99N0vnESqK8oxhp)
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 50
    initial-size: 10
    max-wait: 60000
    max-idle: 20
    min-idle: 10
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
  redis:
    host: 172.16.20.244
    database: 0
    password: redis@duanrong
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0
  rabbitmq:
    host: 172.16.20.249
    port: 5672
    username: jycfmq
    password: jycfmq
    VirtualHost: jycf01
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true
#jasypt:
#  encryptor:
#    password: cashloan



timer:
  get-data-from-fraud:
    servers: 172.16.20.245:8501
    cron: 0 0 0 1 * ?
#  get-data-from-fraud:
#    servers: 192.168.5.94:8501,192.168.5.95:8501
#    cron: 0 0 0 1 * ?